In [8]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [9]:
import pandas as pd 
import numpy as np  
df=pd.read_csv("train.csv")
df_test=pd.read_csv("test.csv")

In [10]:
df.head()

,id,Driver,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change,PitNextLap
0,0,D109,HARD,Canadian Grand Prix,2022,0,50,2,39.0,8,78.491,-7.564,21.019,0.714286,5.0,1.0
1,1,D086,HARD,Dutch Grand Prix,2025,1,27,2,7.0,4,75.095,-32.617,-223.207,0.346154,-3.0,0.0
2,2,ZON,HARD,Austrian Grand Prix,2022,0,59,3,22.0,13,70.945,-7.540,-100.529,0.819444,3.0,1.0
3,3,SPE,MEDIUM,Pre-Season Testing,2023,0,2,1,2.0,7,94.361,-7.324,-7.324,0.076923,0.0,0.0
4,4,D019,HARD,Azerbaijan Grand Prix,2022,1,26,3,6.0,2,107.878,8.965,-14.139,0.361111,3.0,0.0

In [11]:
len(df.columns)

16

In [12]:
import matplotlib.pyplot as py
import seaborn as sns

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439140 entries, 0 to 439139
Data columns (total 16 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      439140 non-null  int64
 1   Driver                  439140 non-null  object
 2   Compound                439140 non-null  object
 3   Race                    439140 non-null  object
 4   Year                    439140 non-null  int64
 5   PitStop                 439140 non-null  int64
 6   LapNumber               439140 non-null  int64
 7   Stint                   439140 non-null  int64
 8   TyreLife                439140 non-null  float64
 9   Position                439140 non-null  int64
 10  LapTime (s)             439140 non-null  float64
 11  LapTime_Delta           439140 non-null  float64
 12  Cumulative_Degradation  439140 non-null  float64
 13  RaceProgress            439140 non-null  float64
 14  Position_Change         439140 non-null  float64
 15  PitNextLap              439140 non-null  float64
dtypes: float64(7), int64(6), object(3)
memory usage: 53.6+ MB

In [14]:
df["Year"].min(),df["Year"].max()

(np.int64(2022), np.int64(2025))

In [15]:
df["Year"].astype(int)-2022  #year between 0-3

0         0
1         3
2         0
3         1
4         0
         ..
439135    1
439136    1
439137    1
439138    1
439139    1
Name: Year, Length: 439140, dtype: int64

In [16]:
df["Compound"].unique()

array(['HARD', 'MEDIUM', 'INTERMEDIATE', 'SOFT', 'WET'], dtype=object)

In [17]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Compound'] = encoder.fit_transform(df['Compound'])

In [18]:
df["Compound"].unique
# to know mapped classes
encoder.classes_
#'HARD'-0, 'INTERMEDIATE'-1, 'MEDIUM'-2, 'SOFT'-3, 'WET'-4

array(['HARD', 'INTERMEDIATE', 'MEDIUM', 'SOFT', 'WET'], dtype=object)

In [19]:
df["Race"].str.replace("Grand Prix","").unique()
encoder=LabelEncoder()

In [20]:
df["Race"]=encoder.fit_transform(df["Race"])
df["Race"].unique().max()

np.int64(25)

In [21]:
len(df["Driver"].unique())

887

In [ ]:
x_train=df[[column for column in df.columns if column != 'PitNextLap' and  column != 'Driver']]
y_train=df['PitNextLap']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(
    x_train,y_train,
    test_size=0.2,
    random_state=42,
    stratify=y_train
)

In [33]:
print(x_train.info())

<class 'pandas.core.frame.DataFrame'>
Index: 351312 entries, 356074 to 121958
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      351312 non-null  int64
 1   Compound                351312 non-null  int64
 2   Race                    351312 non-null  int64
 3   Year                    351312 non-null  int64
 4   PitStop                 351312 non-null  int64
 5   LapNumber               351312 non-null  int64
 6   Stint                   351312 non-null  int64
 7   TyreLife                351312 non-null  float64
 8   Position                351312 non-null  int64
 9   LapTime (s)             351312 non-null  float64
 10  LapTime_Delta           351312 non-null  float64
 11  Cumulative_Degradation  351312 non-null  float64
 12  RaceProgress            351312 non-null  float64
 13  Position_Change         351312 non-null  float64
dtypes: float64(6), int64(8)
memory usage: 40.2 MB
None

In [ ]:
#Binary Classification
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.pipeline import make_pipeline
epochs=1000
learning_rate=0.01
mlp_clf=MLPClassifier(hidden_layer_sizes=[200,200,200],solver='adam',verbose=True,early_stopping=True,batch_size=1024,learning_rate='adaptive',random_state=42)
pipeline=make_pipeline(MinMaxScaler(),mlp_clf)
pipeline.fit(x_train,y_train)
y_proba = pipeline.predict_proba(
    x_test
)[:,1]
y_pred=(y_proba>0.3).astype(int)

Iteration 1, loss = 0.36418987
Validation score: 0.862063
Iteration 2, loss = 0.28558723
Validation score: 0.877775
Iteration 3, loss = 0.27683204
Validation score: 0.878715
Iteration 4, loss = 0.27195030
Validation score: 0.878715
Iteration 5, loss = 0.26839413
Validation score: 0.881504
Iteration 6, loss = 0.26602724
Validation score: 0.880166
Iteration 7, loss = 0.26454115
Validation score: 0.881931
Iteration 8, loss = 0.26379808
Validation score: 0.882130
Iteration 9, loss = 0.26244187
Validation score: 0.883269
Iteration 10, loss = 0.26050284
Validation score: 0.881049
Iteration 11, loss = 0.26003078
Validation score: 0.883553
Iteration 12, loss = 0.25967228
Validation score: 0.880052
Iteration 13, loss = 0.25854281
Validation score: 0.884436
Iteration 14, loss = 0.25795818
Validation score: 0.883212
Iteration 15, loss = 0.25692066
Validation score: 0.883468
Iteration 16, loss = 0.25663764
Validation score: 0.883269
Iteration 17, loss = 0.25550338
Validation score: 0.885034
Iteration 18, loss = 0.25487517
Validation score: 0.883952
Iteration 19, loss = 0.25487582
Validation score: 0.884635
Iteration 20, loss = 0.25388307
Validation score: 0.885461
Iteration 21, loss = 0.25355534
Validation score: 0.884891
Iteration 22, loss = 0.25240629
Validation score: 0.884948
Iteration 23, loss = 0.25218923
Validation score: 0.886912
Iteration 24, loss = 0.25104348
Validation score: 0.885233
Iteration 25, loss = 0.25064502
Validation score: 0.886229
Iteration 26, loss = 0.25012850
Validation score: 0.885916
Iteration 27, loss = 0.24963151
Validation score: 0.886371
Iteration 28, loss = 0.24911002
Validation score: 0.888335
Iteration 29, loss = 0.24872424
Validation score: 0.887681
Iteration 30, loss = 0.24780562
Validation score: 0.886172
Iteration 31, loss = 0.24762156
Validation score: 0.886172
Iteration 32, loss = 0.24717911
Validation score: 0.885802
Iteration 33, loss = 0.24597275
Validation score: 0.887339
Iteration 34, loss = 0.24604663
Validation score: 0.887282
Iteration 35, loss = 0.24574545
Validation score: 0.886144
Iteration 36, loss = 0.24524579
Validation score: 0.887595
Iteration 37, loss = 0.24484805
Validation score: 0.887510
Iteration 38, loss = 0.24373046
Validation score: 0.887994
Iteration 39, loss = 0.24389723
Validation score: 0.888108
Validation score did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

C:\Users\bishe\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

ValueError: Expected a 2-dimensional container but got <class 'pandas.core.series.Series'> instead. Pass a DataFrame containing a single row (i.e. single sample) or a single column (i.e. single feature) instead.

In [43]:
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    roc_auc_score,
    f1_score
)
accuracy=accuracy_score(y_test,y_pred) # 0.888108
print(accuracy)
print(classification_report(y_test, y_pred))

0.8753244978822243
              precision    recall  f1-score   support

         0.0       0.96      0.88      0.92     70286
         1.0       0.64      0.86      0.73     17542

    accuracy                           0.88     87828
   macro avg       0.80      0.87      0.83     87828
weighted avg       0.90      0.88      0.88     87828

In [44]:
#train the model on the whole data
x=df[[column for column in df.columns if column != 'PitNextLap' and  column != 'Driver']]
y=df['PitNextLap']
pipeline.fit(x,y)


df_test["Year"].astype(int)-2022
df_test['Compound'] = encoder.fit_transform(df_test['Compound'])
df_test["Race"]=encoder.fit_transform(df_test["Race"])
df_test.info()

Iteration 1, loss = 0.34884718
Validation score: 0.877032
Iteration 2, loss = 0.28238945
Validation score: 0.879697
Iteration 3, loss = 0.27435157
Validation score: 0.882725
Iteration 4, loss = 0.26978215
Validation score: 0.884775
Iteration 5, loss = 0.26661720
Validation score: 0.883796
Iteration 6, loss = 0.26360089
Validation score: 0.886847
Iteration 7, loss = 0.26178792
Validation score: 0.886437
Iteration 8, loss = 0.26085744
Validation score: 0.886027
Iteration 9, loss = 0.25897450
Validation score: 0.886437
Iteration 10, loss = 0.25824482
Validation score: 0.887280
Iteration 11, loss = 0.25699057
Validation score: 0.886073
Iteration 12, loss = 0.25636046
Validation score: 0.888487
Iteration 13, loss = 0.25552386
Validation score: 0.887325
Iteration 14, loss = 0.25493315
Validation score: 0.888145
Iteration 15, loss = 0.25399747
Validation score: 0.888487
Iteration 16, loss = 0.25301911
Validation score: 0.889261
Iteration 17, loss = 0.25232338
Validation score: 0.889693
Iteration 18, loss = 0.25229746
Validation score: 0.888008
Iteration 19, loss = 0.25108000
Validation score: 0.888350
Iteration 20, loss = 0.25060819
Validation score: 0.888805
Iteration 21, loss = 0.24943397
Validation score: 0.890536
Iteration 22, loss = 0.24961475
Validation score: 0.889010
Iteration 23, loss = 0.24928200
Validation score: 0.890673
Iteration 24, loss = 0.24830638
Validation score: 0.890673
Iteration 25, loss = 0.24800839
Validation score: 0.891310
Iteration 26, loss = 0.24742785
Validation score: 0.890718
Iteration 27, loss = 0.24693158
Validation score: 0.890604
Iteration 28, loss = 0.24638698
Validation score: 0.889557
Iteration 29, loss = 0.24558605
Validation score: 0.889124
Iteration 30, loss = 0.24547552
Validation score: 0.890650
Iteration 31, loss = 0.24439603
Validation score: 0.889511
Iteration 32, loss = 0.24425208
Validation score: 0.889990
Iteration 33, loss = 0.24431640
Validation score: 0.891265
Iteration 34, loss = 0.24365922
Validation score: 0.892813
Iteration 35, loss = 0.24332590
Validation score: 0.891083
Iteration 36, loss = 0.24246848
Validation score: 0.890354
Iteration 37, loss = 0.24197175
Validation score: 0.891424
Iteration 38, loss = 0.24202390
Validation score: 0.890559
Iteration 39, loss = 0.24181332
Validation score: 0.891196
Iteration 40, loss = 0.24133365
Validation score: 0.892221
Iteration 41, loss = 0.24068933
Validation score: 0.890878
Iteration 42, loss = 0.24105232
Validation score: 0.890809
Iteration 43, loss = 0.23973079
Validation score: 0.890695
Iteration 44, loss = 0.23982131
Validation score: 0.892358
Iteration 45, loss = 0.23921777
Validation score: 0.891629
Validation score did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 188165 entries, 0 to 188164
Data columns (total 15 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      188165 non-null  int64
 1   Driver                  188165 non-null  object
 2   Compound                188165 non-null  int64
 3   Race                    188165 non-null  int64
 4   Year                    188165 non-null  int64
 5   PitStop                 188165 non-null  int64
 6   LapNumber               188165 non-null  int64
 7   Stint                   188165 non-null  int64
 8   TyreLife                188165 non-null  float64
 9   Position                188165 non-null  int64
 10  LapTime (s)             188165 non-null  float64
 11  LapTime_Delta           188165 non-null  float64
 12  Cumulative_Degradation  188165 non-null  float64
 13  RaceProgress            188165 non-null  float64
 14  Position_Change         188165 non-null  float64
dtypes: float64(6), int64(8), object(1)
memory usage: 21.5+ MB

In [45]:
x_test_final=df_test[
    [
        column for column in df.columns
        if column not in ['Driver', 'PitNextLap']
    ]
]
x_test_final.head()

,id,Compound,Race,Year,PitStop,LapNumber,Stint,TyreLife,Position,LapTime (s),LapTime_Delta,Cumulative_Degradation,RaceProgress,Position_Change
0,439140,2,6,2023,0,21,1,21.0,4,93.387,0.280,-4.984,0.403846,0.0
1,439141,2,0,2023,0,24,1,24.0,1,90.867,-0.129,-1.990,0.413793,0.0
2,439142,2,6,2023,0,24,1,24.0,11,92.871,0.041,-8.842,0.461538,0.0
3,439143,3,24,2024,0,6,2,4.0,15,94.967,-19.741,8.250,0.077922,1.0
4,439144,0,25,2024,0,52,2,29.0,12,99.112,0.930,-20.848,0.722222,7.0

In [46]:
df_test.shape
x_test_final.shape

(188165, 14)

In [47]:

y_pred_final = pipeline.predict(x_test_final)

submission = pd.DataFrame({
    'id': x_test_final['id'],
    'PitNextStop': y_pred_final.astype(int)
})

submission.to_csv('submission.csv', index=False)
print(submission.head())

       id  PitNextStop
0  439140            0
1  439141            0
2  439142            0
3  439143            0
4  439144            1

In [48]:
(y_pred_final==1).sum()

np.int64(35936)

In [51]:
x_train_xgboost=df[[column for column in df.columns if column != 'PitNextLap' and  column != 'Driver']]
y_train_xgboost=df['PitNextLap']
from sklearn.model_selection import train_test_split
x_train_xgboost,x_test_xgboost,y_train_xgboost,y_test_xgboost=train_test_split(
    x_train_xgboost,y_train_xgboost,
    test_size=0.2,
    random_state=42,
    stratify=y_train_xgboost
)

In [52]:
x_train_xgboost.info()

<class 'pandas.core.frame.DataFrame'>
Index: 351312 entries, 152811 to 96127
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      351312 non-null  int64
 1   Compound                351312 non-null  int64
 2   Race                    351312 non-null  int64
 3   Year                    351312 non-null  int64
 4   PitStop                 351312 non-null  int64
 5   LapNumber               351312 non-null  int64
 6   Stint                   351312 non-null  int64
 7   TyreLife                351312 non-null  float64
 8   Position                351312 non-null  int64
 9   LapTime (s)             351312 non-null  float64
 10  LapTime_Delta           351312 non-null  float64
 11  Cumulative_Degradation  351312 non-null  float64
 12  RaceProgress            351312 non-null  float64
 13  Position_Change         351312 non-null  float64
dtypes: float64(6), int64(8)
memory usage: 40.2 MB

In [62]:
#Applying Hyperparameter Tuning to XGBoost
import numpy as np
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV


# Handle class imbalance
scale_pos_weight = (
    (y_train_xgboost == 0).sum()
    /
    (y_train_xgboost == 1).sum()
)

# Base XGBoost model
xgb_clf = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    scale_pos_weight=scale_pos_weight,
    random_state=42
)

# Hyperparameter search space
param_dist = {

    'n_estimators': [200, 500, 800],
    'learning_rate': [0.01, 0.05, 0.1],
    'max_depth': [4, 6, 8],
    'subsample': [0.7, 0.8, 1.0],
    'colsample_bytree': [0.7, 0.8, 1.0],
    'min_child_weight': [1, 3, 5],
    'gamma': [0, 0.1, 0.3]
}

# Randomized Search
random_search = RandomizedSearchCV(

    estimator=xgb_clf,

    param_distributions=param_dist,

    n_iter=15,

    scoring='roc_auc',

    cv=3,

    verbose=2,

    random_state=42,

    n_jobs=-1
)

# Train
random_search.fit(
    x_train_xgboost,
    y_train_xgboost
)
random_search.best_params_ #taking best parameters

Fitting 3 folds for each of 15 candidates, totalling 45 fits

{'subsample': 1.0,
 'n_estimators': 500,
 'min_child_weight': 5,
 'max_depth': 8,
 'learning_rate': 0.05,
 'gamma': 0.1,
 'colsample_bytree': 0.8}

In [65]:
#Applying XgBoost along with optimizing hyperparameters
from xgboost import XGBClassifier
xgb_clf = XGBClassifier(
    objective='binary:logistic',
    eval_metric='auc',
    subsample=1.0,
    n_estimators= 500,
    min_child_weight= 5,
 max_depth= 8,
 learning_rate= 0.05,
 gamma= 0.1,
 colsample_bytree=0.8
)
#hyperparameter tuning using cv

from sklearn.metrics import (
    accuracy_score, 
    classification_report,)
xgb_clf.fit(x_train_xgboost,y_train_xgboost,eval_set=[(x_test_xgboost,y_test_xgboost)],verbose=True)
y_pred_xgb=xgb_clf.predict(x_test_xgboost)
accuracy_xgb=accuracy_score(y_test_xgboost,y_pred_xgb)
print(accuracy_xgb) 
print(classification_report(y_test_xgboost,y_pred_xgb))

[0]	validation_0-auc:0.88651
[1]	validation_0-auc:0.92165
[2]	validation_0-auc:0.92151
[3]	validation_0-auc:0.92335
[4]	validation_0-auc:0.92668
[5]	validation_0-auc:0.92806
[6]	validation_0-auc:0.92889
[7]	validation_0-auc:0.92913
[8]	validation_0-auc:0.93004
[9]	validation_0-auc:0.93078
[10]	validation_0-auc:0.93105
[11]	validation_0-auc:0.93168
[12]	validation_0-auc:0.93190
[13]	validation_0-auc:0.93201
[14]	validation_0-auc:0.93235
[15]	validation_0-auc:0.93257
[16]	validation_0-auc:0.93293
[17]	validation_0-auc:0.93344
[18]	validation_0-auc:0.93373
[19]	validation_0-auc:0.93390
[20]	validation_0-auc:0.93410
[21]	validation_0-auc:0.93430
[22]	validation_0-auc:0.93444
[23]	validation_0-auc:0.93456
[24]	validation_0-auc:0.93473
[25]	validation_0-auc:0.93502
[26]	validation_0-auc:0.93523
[27]	validation_0-auc:0.93554
[28]	validation_0-auc:0.93573
[29]	validation_0-auc:0.93589
[30]	validation_0-auc:0.93612
[31]	validation_0-auc:0.93624
[32]	validation_0-auc:0.93656
[33]	validation_0-auc:0.93676
[34]	validation_0-auc:0.93696
[35]	validation_0-auc:0.93708
[36]	validation_0-auc:0.93721
[37]	validation_0-auc:0.93746
[38]	validation_0-auc:0.93757
[39]	validation_0-auc:0.93778
[40]	validation_0-auc:0.93787
[41]	validation_0-auc:0.93811
[42]	validation_0-auc:0.93821
[43]	validation_0-auc:0.93837
[44]	validation_0-auc:0.93847
[45]	validation_0-auc:0.93859
[46]	validation_0-auc:0.93868
[47]	validation_0-auc:0.93872
[48]	validation_0-auc:0.93890
[49]	validation_0-auc:0.93906
[50]	validation_0-auc:0.93913
[51]	validation_0-auc:0.93920
[52]	validation_0-auc:0.93931
[53]	validation_0-auc:0.93944
[54]	validation_0-auc:0.93966
[55]	validation_0-auc:0.93979
[56]	validation_0-auc:0.93989
[57]	validation_0-auc:0.93995
[58]	validation_0-auc:0.94001
[59]	validation_0-auc:0.94005
[60]	validation_0-auc:0.94015
[61]	validation_0-auc:0.94040
[62]	validation_0-auc:0.94056
[63]	validation_0-auc:0.94062
[64]	validation_0-auc:0.94072
[65]	validation_0-auc:0.94078
[66]	validation_0-auc:0.94086
[67]	validation_0-auc:0.94103
[68]	validation_0-auc:0.94113
[69]	validation_0-auc:0.94127
[70]	validation_0-auc:0.94137
[71]	validation_0-auc:0.94142
[72]	validation_0-auc:0.94152
[73]	validation_0-auc:0.94164
[74]	validation_0-auc:0.94173
[75]	validation_0-auc:0.94183
[76]	validation_0-auc:0.94192
[77]	validation_0-auc:0.94203
[78]	validation_0-auc:0.94213
[79]	validation_0-auc:0.94222
[80]	validation_0-auc:0.94227
[81]	validation_0-auc:0.94250
[82]	validation_0-auc:0.94255
[83]	validation_0-auc:0.94263
[84]	validation_0-auc:0.94268
[85]	validation_0-auc:0.94272
[86]	validation_0-auc:0.94283
[87]	validation_0-auc:0.94288
[88]	validation_0-auc:0.94295
[89]	validation_0-auc:0.94300
[90]	validation_0-auc:0.94304
[91]	validation_0-auc:0.94309
[92]	validation_0-auc:0.94317
[93]	validation_0-auc:0.94326
[94]	validation_0-auc:0.94331
[95]	validation_0-auc:0.94338
[96]	validation_0-auc:0.94340
[97]	validation_0-auc:0.94352
[98]	validation_0-auc:0.94357
[99]	validation_0-auc:0.94361
[100]	validation_0-auc:0.94363
[101]	validation_0-auc:0.94365
[102]	validation_0-auc:0.94367
[103]	validation_0-auc:0.94370
[104]	validation_0-auc:0.94379
[105]	validation_0-auc:0.94386
[106]	validation_0-auc:0.94392
[107]	validation_0-auc:0.94394
[108]	validation_0-auc:0.94396
[109]	validation_0-auc:0.94399
[110]	validation_0-auc:0.94404
[111]	validation_0-auc:0.94409
[112]	validation_0-auc:0.94413
[113]	validation_0-auc:0.94416
[114]	validation_0-auc:0.94421
[115]	validation_0-auc:0.94423
[116]	validation_0-auc:0.94426
[117]	validation_0-auc:0.94429
[118]	validation_0-auc:0.94434
[119]	validation_0-auc:0.94446
[120]	validation_0-auc:0.94450
[121]	validation_0-auc:0.94454
[122]	validation_0-auc:0.94462
[123]	validation_0-auc:0.94478
[124]	validation_0-auc:0.94484
[125]	validation_0-auc:0.94487
[126]	validation_0-auc:0.94497
[127]	validation_0-auc:0.94501
[128]	validation_0-auc:0.94503
[129]	validation_0-auc:0.94508
[130]	validation_0-auc:0.94510
[131]	validation_0-auc:0.94516
[132]	validation_0-auc:0.94520
[133]	validation_0-auc:0.94522
[134]	validation_0-auc:0.94525
[135]	validation_0-auc:0.94529
[136]	validation_0-auc:0.94530
[137]	validation_0-auc:0.94532
[138]	validation_0-auc:0.94535
[139]	validation_0-auc:0.94538
[140]	validation_0-auc:0.94540
[141]	validation_0-auc:0.94543
[142]	validation_0-auc:0.94549
[143]	validation_0-auc:0.94551
[144]	validation_0-auc:0.94555
[145]	validation_0-auc:0.94558
[146]	validation_0-auc:0.94559
[147]	validation_0-auc:0.94561
[148]	validation_0-auc:0.94561
[149]	validation_0-auc:0.94563
[150]	validation_0-auc:0.94564
[151]	validation_0-auc:0.94568
[152]	validation_0-auc:0.94571
[153]	validation_0-auc:0.94573
[154]	validation_0-auc:0.94574
[155]	validation_0-auc:0.94576
[156]	validation_0-auc:0.94578
[157]	validation_0-auc:0.94582
[158]	validation_0-auc:0.94584
[159]	validation_0-auc:0.94586
[160]	validation_0-auc:0.94587
[161]	validation_0-auc:0.94588
[162]	validation_0-auc:0.94590
[163]	validation_0-auc:0.94594
[164]	validation_0-auc:0.94598
[165]	validation_0-auc:0.94600
[166]	validation_0-auc:0.94600
[167]	validation_0-auc:0.94603
[168]	validation_0-auc:0.94603
[169]	validation_0-auc:0.94605
[170]	validation_0-auc:0.94607
[171]	validation_0-auc:0.94609
[172]	validation_0-auc:0.94611
[173]	validation_0-auc:0.94612
[174]	validation_0-auc:0.94615
[175]	validation_0-auc:0.94616
[176]	validation_0-auc:0.94618
[177]	validation_0-auc:0.94618
[178]	validation_0-auc:0.94619
[179]	validation_0-auc:0.94620
[180]	validation_0-auc:0.94623
[181]	validation_0-auc:0.94623
[182]	validation_0-auc:0.94623
[183]	validation_0-auc:0.94625
[184]	validation_0-auc:0.94626
[185]	validation_0-auc:0.94628
[186]	validation_0-auc:0.94632
[187]	validation_0-auc:0.94634
[188]	validation_0-auc:0.94635
[189]	validation_0-auc:0.94635
[190]	validation_0-auc:0.94641
[191]	validation_0-auc:0.94642
[192]	validation_0-auc:0.94643
[193]	validation_0-auc:0.94643
[194]	validation_0-auc:0.94647
[195]	validation_0-auc:0.94649
[196]	validation_0-auc:0.94652
[197]	validation_0-auc:0.94652
[198]	validation_0-auc:0.94654
[199]	validation_0-auc:0.94654
[200]	validation_0-auc:0.94655
[201]	validation_0-auc:0.94655
[202]	validation_0-auc:0.94655
[203]	validation_0-auc:0.94658
[204]	validation_0-auc:0.94659
[205]	validation_0-auc:0.94661
[206]	validation_0-auc:0.94662
[207]	validation_0-auc:0.94663
[208]	validation_0-auc:0.94663
[209]	validation_0-auc:0.94665
[210]	validation_0-auc:0.94665
[211]	validation_0-auc:0.94666
[212]	validation_0-auc:0.94667
[213]	validation_0-auc:0.94668
[214]	validation_0-auc:0.94668
[215]	validation_0-auc:0.94671
[216]	validation_0-auc:0.94673
[217]	validation_0-auc:0.94676
[218]	validation_0-auc:0.94679
[219]	validation_0-auc:0.94680
[220]	validation_0-auc:0.94682
[221]	validation_0-auc:0.94682
[222]	validation_0-auc:0.94682
[223]	validation_0-auc:0.94683
[224]	validation_0-auc:0.94684
[225]	validation_0-auc:0.94685
[226]	validation_0-auc:0.94687
[227]	validation_0-auc:0.94688
[228]	validation_0-auc:0.94691
[229]	validation_0-auc:0.94691
[230]	validation_0-auc:0.94695
[231]	validation_0-auc:0.94697
[232]	validation_0-auc:0.94697
[233]	validation_0-auc:0.94699
[234]	validation_0-auc:0.94699
[235]	validation_0-auc:0.94701
[236]	validation_0-auc:0.94705
[237]	validation_0-auc:0.94706
[238]	validation_0-auc:0.94709
[239]	validation_0-auc:0.94710
[240]	validation_0-auc:0.94710
[241]	validation_0-auc:0.94711
[242]	validation_0-auc:0.94712
[243]	validation_0-auc:0.94712
[244]	validation_0-auc:0.94714
[245]	validation_0-auc:0.94715
[246]	validation_0-auc:0.94716
[247]	validation_0-auc:0.94718
[248]	validation_0-auc:0.94719
[249]	validation_0-auc:0.94720
[250]	validation_0-auc:0.94721
[251]	validation_0-auc:0.94721
[252]	validation_0-auc:0.94721
[253]	validation_0-auc:0.94721
[254]	validation_0-auc:0.94722
[255]	validation_0-auc:0.94722
[256]	validation_0-auc:0.94722
[257]	validation_0-auc:0.94722
[258]	validation_0-auc:0.94724
[259]	validation_0-auc:0.94728
[260]	validation_0-auc:0.94733
[261]	validation_0-auc:0.94734
[262]	validation_0-auc:0.94734
[263]	validation_0-auc:0.94736
[264]	validation_0-auc:0.94736
[265]	validation_0-auc:0.94737
[266]	validation_0-auc:0.94737
[267]	validation_0-auc:0.94739
[268]	validation_0-auc:0.94741
[269]	validation_0-auc:0.94743
[270]	validation_0-auc:0.94744
[271]	validation_0-auc:0.94744
[272]	validation_0-auc:0.94744
[273]	validation_0-auc:0.94745
[274]	validation_0-auc:0.94745
[275]	validation_0-auc:0.94745
[276]	validation_0-auc:0.94746
[277]	validation_0-auc:0.94747
[278]	validation_0-auc:0.94747
[279]	validation_0-auc:0.94747
[280]	validation_0-auc:0.94747
[281]	validation_0-auc:0.94749
[282]	validation_0-auc:0.94750
[283]	validation_0-auc:0.94751
[284]	validation_0-auc:0.94751
[285]	validation_0-auc:0.94752
[286]	validation_0-auc:0.94754
[287]	validation_0-auc:0.94753
[288]	validation_0-auc:0.94753
[289]	validation_0-auc:0.94757
[290]	validation_0-auc:0.94758
[291]	validation_0-auc:0.94758
[292]	validation_0-auc:0.94759
[293]	validation_0-auc:0.94760
[294]	validation_0-auc:0.94761
[295]	validation_0-auc:0.94762
[296]	validation_0-auc:0.94765
[297]	validation_0-auc:0.94766
[298]	validation_0-auc:0.94767
[299]	validation_0-auc:0.94768
[300]	validation_0-auc:0.94769
[301]	validation_0-auc:0.94769
[302]	validation_0-auc:0.94768
[303]	validation_0-auc:0.94770
[304]	validation_0-auc:0.94770
[305]	validation_0-auc:0.94771
[306]	validation_0-auc:0.94772
[307]	validation_0-auc:0.94772
[308]	validation_0-auc:0.94773
[309]	validation_0-auc:0.94774
[310]	validation_0-auc:0.94775
[311]	validation_0-auc:0.94776
[312]	validation_0-auc:0.94776
[313]	validation_0-auc:0.94776
[314]	validation_0-auc:0.94777
[315]	validation_0-auc:0.94781
[316]	validation_0-auc:0.94781
[317]	validation_0-auc:0.94782
[318]	validation_0-auc:0.94783
[319]	validation_0-auc:0.94784
[320]	validation_0-auc:0.94784
[321]	validation_0-auc:0.94785
[322]	validation_0-auc:0.94785
[323]	validation_0-auc:0.94785
[324]	validation_0-auc:0.94786
[325]	validation_0-auc:0.94787
[326]	validation_0-auc:0.94788
[327]	validation_0-auc:0.94788
[328]	validation_0-auc:0.94789
[329]	validation_0-auc:0.94789
[330]	validation_0-auc:0.94789
[331]	validation_0-auc:0.94789
[332]	validation_0-auc:0.94790
[333]	validation_0-auc:0.94789
[334]	validation_0-auc:0.94789
[335]	validation_0-auc:0.94789
[336]	validation_0-auc:0.94789
[337]	validation_0-auc:0.94790
[338]	validation_0-auc:0.94791
[339]	validation_0-auc:0.94791
[340]	validation_0-auc:0.94796
[341]	validation_0-auc:0.94796
[342]	validation_0-auc:0.94797
[343]	validation_0-auc:0.94796
[344]	validation_0-auc:0.94797
[345]	validation_0-auc:0.94801
[346]	validation_0-auc:0.94801
[347]	validation_0-auc:0.94802
[348]	validation_0-auc:0.94803
[349]	validation_0-auc:0.94804
[350]	validation_0-auc:0.94804
[351]	validation_0-auc:0.94804
[352]	validation_0-auc:0.94804
[353]	validation_0-auc:0.94804
[354]	validation_0-auc:0.94804
[355]	validation_0-auc:0.94805
[356]	validation_0-auc:0.94805
[357]	validation_0-auc:0.94807
[358]	validation_0-auc:0.94808
[359]	validation_0-auc:0.94809
[360]	validation_0-auc:0.94809
[361]	validation_0-auc:0.94809
[362]	validation_0-auc:0.94809
[363]	validation_0-auc:0.94810
[364]	validation_0-auc:0.94811
[365]	validation_0-auc:0.94811
[366]	validation_0-auc:0.94811
[367]	validation_0-auc:0.94811
[368]	validation_0-auc:0.94811
[369]	validation_0-auc:0.94811
[370]	validation_0-auc:0.94811
[371]	validation_0-auc:0.94812
[372]	validation_0-auc:0.94813
[373]	validation_0-auc:0.94813
[374]	validation_0-auc:0.94814
[375]	validation_0-auc:0.94813
[376]	validation_0-auc:0.94813
[377]	validation_0-auc:0.94813
[378]	validation_0-auc:0.94814
[379]	validation_0-auc:0.94814
[380]	validation_0-auc:0.94815
[381]	validation_0-auc:0.94816
[382]	validation_0-auc:0.94817
[383]	validation_0-auc:0.94817
[384]	validation_0-auc:0.94818
[385]	validation_0-auc:0.94818
[386]	validation_0-auc:0.94818
[387]	validation_0-auc:0.94818
[388]	validation_0-auc:0.94818
[389]	validation_0-auc:0.94819
[390]	validation_0-auc:0.94819
[391]	validation_0-auc:0.94820
[392]	validation_0-auc:0.94820
[393]	validation_0-auc:0.94821
[394]	validation_0-auc:0.94820
[395]	validation_0-auc:0.94821
[396]	validation_0-auc:0.94821
[397]	validation_0-auc:0.94820
[398]	validation_0-auc:0.94820
[399]	validation_0-auc:0.94821
[400]	validation_0-auc:0.94821
[401]	validation_0-auc:0.94821
[402]	validation_0-auc:0.94821
[403]	validation_0-auc:0.94823
[404]	validation_0-auc:0.94823
[405]	validation_0-auc:0.94823
[406]	validation_0-auc:0.94825
[407]	validation_0-auc:0.94825
[408]	validation_0-auc:0.94825
[409]	validation_0-auc:0.94826
[410]	validation_0-auc:0.94826
[411]	validation_0-auc:0.94826
[412]	validation_0-auc:0.94827
[413]	validation_0-auc:0.94828
[414]	validation_0-auc:0.94828
[415]	validation_0-auc:0.94829
[416]	validation_0-auc:0.94830
[417]	validation_0-auc:0.94829
[418]	validation_0-auc:0.94831
[419]	validation_0-auc:0.94831
[420]	validation_0-auc:0.94832
[421]	validation_0-auc:0.94832
[422]	validation_0-auc:0.94832
[423]	validation_0-auc:0.94832
[424]	validation_0-auc:0.94832
[425]	validation_0-auc:0.94836
[426]	validation_0-auc:0.94835
[427]	validation_0-auc:0.94836
[428]	validation_0-auc:0.94836
[429]	validation_0-auc:0.94836
[430]	validation_0-auc:0.94838
[431]	validation_0-auc:0.94838
[432]	validation_0-auc:0.94838
[433]	validation_0-auc:0.94841
[434]	validation_0-auc:0.94841
[435]	validation_0-auc:0.94841
[436]	validation_0-auc:0.94841
[437]	validation_0-auc:0.94841
[438]	validation_0-auc:0.94841
[439]	validation_0-auc:0.94840
[440]	validation_0-auc:0.94841
[441]	validation_0-auc:0.94842
[442]	validation_0-auc:0.94842
[443]	validation_0-auc:0.94843
[444]	validation_0-auc:0.94843
[445]	validation_0-auc:0.94842
[446]	validation_0-auc:0.94842
[447]	validation_0-auc:0.94842
[448]	validation_0-auc:0.94841
[449]	validation_0-auc:0.94841
[450]	validation_0-auc:0.94840
[451]	validation_0-auc:0.94840
[452]	validation_0-auc:0.94841
[453]	validation_0-auc:0.94841
[454]	validation_0-auc:0.94841
[455]	validation_0-auc:0.94842
[456]	validation_0-auc:0.94842
[457]	validation_0-auc:0.94844
[458]	validation_0-auc:0.94844
[459]	validation_0-auc:0.94844
[460]	validation_0-auc:0.94845
[461]	validation_0-auc:0.94845
[462]	validation_0-auc:0.94845
[463]	validation_0-auc:0.94847
[464]	validation_0-auc:0.94847
[465]	validation_0-auc:0.94847
[466]	validation_0-auc:0.94847
[467]	validation_0-auc:0.94847
[468]	validation_0-auc:0.94847
[469]	validation_0-auc:0.94847
[470]	validation_0-auc:0.94846
[471]	validation_0-auc:0.94846
[472]	validation_0-auc:0.94847
[473]	validation_0-auc:0.94848
[474]	validation_0-auc:0.94848
[475]	validation_0-auc:0.94848
[476]	validation_0-auc:0.94847
[477]	validation_0-auc:0.94847
[478]	validation_0-auc:0.94848
[479]	validation_0-auc:0.94849
[480]	validation_0-auc:0.94849
[481]	validation_0-auc:0.94849
[482]	validation_0-auc:0.94849
[483]	validation_0-auc:0.94849
[484]	validation_0-auc:0.94849
[485]	validation_0-auc:0.94849
[486]	validation_0-auc:0.94849
[487]	validation_0-auc:0.94849
[488]	validation_0-auc:0.94849
[489]	validation_0-auc:0.94850
[490]	validation_0-auc:0.94851
[491]	validation_0-auc:0.94851
[492]	validation_0-auc:0.94851
[493]	validation_0-auc:0.94853
[494]	validation_0-auc:0.94853
[495]	validation_0-auc:0.94853
[496]	validation_0-auc:0.94853
[497]	validation_0-auc:0.94853
[498]	validation_0-auc:0.94853
[499]	validation_0-auc:0.94853
0.8979141048412806
              precision    recall  f1-score   support

         0.0       0.93      0.94      0.94     70352
         1.0       0.75      0.73      0.74     17476

    accuracy                           0.90     87828
   macro avg       0.84      0.83      0.84     87828
weighted avg       0.90      0.90      0.90     87828

In [60]:
scale_pos_weight = (
    (y_train_xgboost == 0).sum()
    /
    (y_train_xgboost == 1).sum()
)
print(scale_pos_weight)

4.025563264430298

In [67]:
y_pred_final = xgb_clf.predict(x_test_final)

submission = pd.DataFrame({
    'id': x_test_final['id'],
    'PitNextStop': y_pred_final.astype(int)
})

submission.to_csv('submission2.csv', index=False)
print(submission.head())

       id  PitNextStop
0  439140            0
1  439141            0
2  439142            0
3  439143            0
4  439144            1